image: "docker.elastic.co/elasticsearch/elasticsearch-oss"
clusterName: elasticsearch
replicas: 1
minimumMasterNodes: 1
resources:
  requests:
    cpu: "250m"
    memory: "1024Mi"
  limits:
    cpu: "500m"
    memory: "1024Mi"
esJavaOpts: "-Xmx380m -Xms380m"
persistence:
  enabled: true
labels:
  branch: "$BRANCH_NAME"
  resource: pod
  team: platform
  usage: preview
service:
  labels:
    branch: "$BRANCH_NAME"
    resource: service
    team: platform
    usage: preview
tolerations:
  - key: team
    operator: Equal
    value: platform
    effect: NoSchedule
nodeSelector:
  team: platform

