image:
  tag: "4.4.1"
usePassword: false
serviceAccount:
  create: false
resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "2"
    memory: "2Gi"
useStatefulSet: true
persistence:
  enabled: true
labels:
  branch: "$BRANCH_NAME"
  resource: statefulset
  team: platform
  usage: preview
podLabels:
  branch: "$BRANCH_NAME"
  resource: pod
  team: platform
  usage: preview
tolerations:
  - key: team
    operator: Equal
    value: platform
    effect: NoSchedule
nodeSelector:
  team: platform
