nuxeo:
  fullnameOverride: preview
  podAnnotations:
    preview/scm.ref: ${SCM_REF}
  podLabels:
    branch: "$BRANCH_NAME"
    team: platform
    resource: pod
    usage: preview
  service:
    labels:
      branch: "$BRANCH_NAME"
      team: platform
      resource: service
      usage: preview
  image:
    repository: ${DOCKER_REGISTRY}/nuxeo/nuxeo-explorer
    tag: ${VERSION}
    pullPolicy: Always
    pullSecrets:
    - name: kubernetes-docker-cfg
  customEnvs:
  - name: NUXEO_CLID
    valueFrom:
      secretKeyRef:
        name: instance-clid
        key: instance.clid
  customProperties:
    nuxeotemplates: |
      ${NUXEO_TEMPLATE_OVERRIDE}
    explorerconf: |
      ${NUXEO_EXPLORER_CUSTOM_PARAMS}
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/server-snippet: ignore_invalid_headers off;
    hostname: preview-${PREVIEW_NAMESPACE}.platform.dev.nuxeo.com
    tls:
    - hosts:
      - preview-${PREVIEW_NAMESPACE}.platform.dev.nuxeo.com
      secretName: platform-cluster-tls
  persistentVolumeStorage:
    enabled: ${PERSISTENCE}
    size: "100Mi"
  logs:
    persistence:
      enabled: ${PERSISTENCE}
      size: "100Mi"
  mongodb:
    enabled: ${PERSISTENCE}
    host: mongodb.${PREVIEW_NAMESPACE}.svc.cluster.local
  elasticsearch:
    enabled: ${PERSISTENCE}
    host: elasticsearch-master.${PREVIEW_NAMESPACE}.svc.cluster.local
  nodeSelector:
    team: platform
  tolerations:
  - effect: NoSchedule
    key: team
    operator: Equal
    value: platform

# needed for instance-clid replicator and local usage
local:
  instance_clid:
