# (C) Copyright 2019-2020 Nuxeo (http://nuxeo.com/) and others.
#
# Contributors:
#     Kevin Leturc <kleturc@nuxeo.com>
#     Anahide Tchertchian
#
apiVersion: skaffold/v2beta17
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
    - image: "$DOCKER_REGISTRY/nuxeo/nuxeo-explorer"
      context: docker/nuxeo-explorer-docker
      kaniko:
        useNewRun: true
        singleSnapshot: true
        snapshotMode: "time"
        dockerfile: Dockerfile
        buildContext:
          localDir: {}
        buildArgs:
          BASE_IMAGE: ${NUXEO_DOCKER_REGISTRY}/nuxeo/nuxeo:${NUXEO_IMAGE_VERSION}
          BUILD_TAG: "{{.BUILD_TAG}}"
          SCM_REF: "{{.SCM_REF}}"
          VERSION: "{{.VERSION}}"
        cache:
          repo: ${DOCKER_REGISTRY}/nuxeo/nuxeo-explorer/cache
  cluster:
    namespace: platform
    dockerConfig:
      secretName: jenkins-docker-cfg
    resources:
      requests:
        cpu: "1"
        memory: "3Gi"
      limits:
        cpu: "2"
        memory: "6Gi"
    tolerations:
      - key: team
        operator: "Equal"
        value: platform
        effect: "NoSchedule"
