# (C) Copyright 2019-2020 Nuxeo (http://nuxeo.com/) and others.
#
# Contributors:
#     Kevin Leturc <kleturc@nuxeo.com>
#     Anahide Tchertchian
#
apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/nuxeo/{{.IMAGE_NAME}}:{{.VERSION}}"
  artifacts:
    - image: nuxeo-explorer
      context: docker/nuxeo-explorer-docker
      kaniko:
        dockerfile: Dockerfile
        buildContext:
          localDir: {}
        buildArgs:
          BASE_IMAGE: ${NUXEO_DOCKER_REGISTRY}/nuxeo/nuxeo:${NUXEO_IMAGE_VERSION}
          BUILD_TAG: "{{.BUILD_TAG}}"
          SCM_REF: "{{.SCM_REF}}"
          VERSION: "{{.VERSION}}"
        cache:
          repo: ${DOCKER_REGISTRY}/nuxeo/nuxeo-explorer/cache
  cluster:
    namespace: platform
    dockerConfig:
      secretName: jenkins-docker-cfg
# as the image is not available in docker daemon because built by kanino and thus container-structure-tests can not find it
# furthermore, passing --pull arguments to container-structure-tests doesn't do the work as it didn't leverage docker config for auth
# see https://github.com/GoogleContainerTools/skaffold/issues/3907
#test:
#  - image: nuxeo-explorer
#    structureTests:
#      - './docker/nuxeo-explorer-docker/test/*'
